pm uninstall --user 0 com.google.android.youtube
pm uninstall --user 0 com.android.chrome
pm uninstall --user 0 com.google.android.apps.subscriptions.red
pm uninstall --user 0 com.google.android.apps.googleassistant
pm uninstall --user 0 com.google.android.googlequicksearchbox
pm uninstall --user 0 com.android.hotwordenrollment.xgoogle
pm uninstall --user 0 com.google.android.projection.gearhead
pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
pm uninstall --user 0 com.miui.notes
pm uninstall --user 0 com.miui.android.fashiongallery
pm uninstall --user 0 com.miui.cleaner
pm uninstall --user 0 com.xiaomi.mipicks
pm uninstall --user 0 com.miui.msa.global
pm uninstall --user 0 com.miui.weather2
pm uninstall --user 0 com.google.android.tts
pm uninstall --user 0 com.mi.android.globalminusscreen
pm uninstall --user 0 com.google.android.marvin.talkback
pm uninstall --user 0 com.micredit.in
pm uninstall --user 0 com.miui.global.packageinstaller
pm disable-user --user 0 com.miui.analytics